<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="C:\Users\Lenovo\source\repos\ClientForm.cs" Link="ClientForm.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Desktop.Robot" Version="1.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView" Version="10.0.5" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Apphost">
      <HintPath>..\..\Apphost\Apphost\bin\x64\Release\net8.0-windows\Apphost.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>